import React, { useMemo, useRef, useState } from 'react';
import { FileText, Download, Copy, Check, Lightbulb, Eye, Type } from 'lucide-react';
import { toast } from 'react-toastify';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

interface FileViewerProps {
  file: File;
  content: string;
  onClose: () => void;
}

export function FileViewer({ file, content, onClose }: FileViewerProps) {
  const [viewMode, setViewMode] = useState<'rendered' | 'text'>('rendered');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const plainText = useMemo(() => {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(content, 'text/html');
      return doc.body.textContent || '';
    } catch {
      return content;
    }
  }, [content]);
  const previewDocument = useMemo(() => {
    const hasHtmlWrapper = /<html[\s>]/i.test(content);
    if (hasHtmlWrapper) {
      return content;
    }
    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
${content}
</body>
</html>`;
  }, [content]);

  const convertToPDF = async () => {
    if (!contentRef.current) return;
    setIsGenerating(true);
    let tempDiv: HTMLDivElement | null = null;

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const footerSpace = 10;
      const contentWidth = pageWidth - margin * 2;
      const contentHeight = pageHeight - margin * 2 - footerSpace;

      // Set PDF metadata
      const fileName = file.name || 'noname';
      pdf.setProperties({
        title: `${fileName} - UniApplyForMe UNISA Noname Viewer`,
        subject: 'UNISA Noname File Conversion',
        author: 'UniApplyForMe',
        creator: 'UniApplyForMe UNISA Noname Viewer',
        producer: 'UniApplyForMe'
      });

      // Create a temporary div for rendering
      tempDiv = document.createElement('div');
      tempDiv.innerHTML = content;
      tempDiv.style.width = '800px';
      tempDiv.style.padding = '20px';
      document.body.appendChild(tempDiv);

      // Capture the content
      const canvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff'
      });

      // Calculate dimensions
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const imgData = canvas.toDataURL('image/png');

      // Render long documents across multiple pages.
      let heightLeft = imgHeight;
      let yPosition = margin;
      pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
      heightLeft -= contentHeight;

      while (heightLeft > 0) {
        pdf.addPage();
        yPosition = margin - (imgHeight - heightLeft);
        pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
        heightLeft -= contentHeight;
      }

      // Add footer text on each page.
      const totalPages = pdf.getNumberOfPages();
      pdf.setFontSize(10);
      for (let pageIndex = 1; pageIndex <= totalPages; pageIndex += 1) {
        pdf.setPage(pageIndex);
        const footerY = pageHeight - 8;
        pdf.setTextColor(22, 166, 55); // #16a637
        pdf.text('Generated by UniApplyForMe', margin, footerY);
        pdf.setTextColor(9, 94, 65); // #095e41
        pdf.text(`Page ${pageIndex} of ${totalPages}`, pageWidth / 2, footerY, { align: 'center' });
        pdf.text('apply.org.za', pageWidth - margin - 20, footerY);
      }

      // Save the PDF
      pdf.save(`${file.name || 'document'}.pdf`);
      toast.success(`Successfully converted to PDF: ${file.name || 'document'}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      const errorMsg = error instanceof Error ? error.message : 'Failed to generate PDF. Please try again.';
      toast.error(errorMsg);
    } finally {
      if (tempDiv && document.body.contains(tempDiv)) {
        document.body.removeChild(tempDiv);
      }
      setIsGenerating(false);
    }
  };

  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(plainText);
      setCopied(true);
      toast.success('Text copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy text');
      console.error(err);
    }
  };

  return (
    <div className="w-full">
      <Card className="shadow-lg overflow-hidden">
        <Tabs value={viewMode} onValueChange={(value) => setViewMode(value as 'rendered' | 'text')}>
          <CardHeader className="bg-gradient-to-r from-primary/10 to-secondary/10 p-4 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <FileText className="w-6 h-6 sm:w-7 sm:h-7 text-primary flex-shrink-0" />
                <div>
                  <p className="text-xs sm:text-sm text-gray-600">Your file</p>
                  <h2 className="text-base sm:text-lg font-bold text-secondary truncate">
                    {file.name}
                  </h2>
                </div>
              </div>
              <div className="text-right">
                <p className="text-xs text-gray-500">
                  {(file.size / 1024).toFixed(2)} KB
                </p>
              </div>
            </div>

            <div className="flex gap-3 flex-wrap items-center">
              <TabsList className="bg-white/80 border border-primary/20 rounded-xl p-1 h-auto">
                <TabsTrigger value="rendered" className="rounded-lg px-4 py-2 gap-2">
                  <Eye className="w-4 h-4" />
                  Document View
                </TabsTrigger>
                <TabsTrigger value="text" className="rounded-lg px-4 py-2 gap-2">
                  <Type className="w-4 h-4" />
                  Copyable Text
                </TabsTrigger>
              </TabsList>

              <div className="flex gap-2 ml-auto">
                <Button
                  onClick={convertToPDF}
                  disabled={isGenerating}
                  className="text-sm"
                >
                  <Download className="w-4 h-4 mr-2" />
                  {isGenerating ? 'Preparing PDF...' : 'Download PDF'}
                </Button>
                <Button
                  onClick={onClose}
                  variant="outline"
                  className="text-sm"
                >
                  Upload another file
                </Button>
              </div>
            </div>
          </CardHeader>

          <CardContent className="p-4 sm:p-6">
            <TabsContent value="rendered" className="mt-0">
              <div ref={contentRef}>
                <iframe
                  title="Document preview"
                  className="w-full min-h-[56vh] bg-white border border-gray-200 rounded-lg shadow-sm"
                  sandbox="allow-same-origin allow-popups"
                  referrerPolicy="no-referrer"
                  srcDoc={previewDocument}
                />
              </div>
            </TabsContent>

            <TabsContent value="text" className="mt-0">
              <div className="space-y-3">
                <div className="flex justify-end">
                  <Button
                    onClick={handleCopyText}
                    variant="outline"
                    size="sm"
                    className="text-xs sm:text-sm"
                  >
                    {copied ? (
                      <>
                        <Check className="w-4 h-4 mr-2" />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4 mr-2" />
                        Copy text
                      </>
                    )}
                  </Button>
                </div>

                <div className="bg-gray-50 rounded-lg p-4 max-h-[56vh] overflow-auto border border-gray-200">
                  <pre className="whitespace-pre-wrap font-sans text-sm text-gray-900 break-words leading-relaxed">
                    {plainText}
                  </pre>
                </div>
              </div>
            </TabsContent>
          </CardContent>
        </Tabs>

        <div className="bg-gray-50 border-t border-gray-200 px-4 sm:px-6 py-3 text-xs sm:text-sm text-gray-600">
          <p className="flex items-center gap-2">
            <Lightbulb className="w-4 h-4 flex-shrink-0" />
            Switch between document view and plain text, then copy what you need.
          </p>
        </div>
      </Card>
    </div>
  );
}