import React, { useMemo, useRef, useState } from 'react';
import { FileText, Download, Copy, Check, Eye, Type, X, Lightbulb } from 'lucide-react';
import { toast } from 'react-toastify';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

interface FileViewerProps {
  file: File;
  content: string;
  onClose: () => void;
}

export function FileViewer({ file, content, onClose }: FileViewerProps) {
  const [viewMode, setViewMode] = useState<'rendered' | 'text'>('rendered');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const plainText = useMemo(() => {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(content, 'text/html');
      return doc.body.textContent || '';
    } catch {
      return content;
    }
  }, [content]);

  const previewDocument = useMemo(() => {
    if (/<html[\s>]/i.test(content)) return content;
    return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body>${content}</body></html>`;
  }, [content]);

  const convertToPDF = async () => {
    if (!contentRef.current) return;
    setIsGenerating(true);
    let tempDiv: HTMLDivElement | null = null;

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      const footerSpace = 10;
      const contentWidth = pageWidth - margin * 2;
      const contentHeight = pageHeight - margin * 2 - footerSpace;

      pdf.setProperties({
        title: `${file.name} - UniApplyForMe UNISA Noname Viewer`,
        subject: 'UNISA Noname File Conversion',
        author: 'UniApplyForMe',
        creator: 'UniApplyForMe UNISA Noname Viewer',
        producer: 'UniApplyForMe',
      });

      tempDiv = document.createElement('div');
      tempDiv.innerHTML = content;
      tempDiv.style.width = '800px';
      tempDiv.style.padding = '20px';
      document.body.appendChild(tempDiv);

      const canvas = await html2canvas(tempDiv, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const imgData = canvas.toDataURL('image/png');

      let heightLeft = imgHeight;
      let yPosition = margin;
      pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
      heightLeft -= contentHeight;

      while (heightLeft > 0) {
        pdf.addPage();
        yPosition = margin - (imgHeight - heightLeft);
        pdf.addImage(imgData, 'PNG', margin, yPosition, imgWidth, imgHeight);
        heightLeft -= contentHeight;
      }

      const totalPages = pdf.getNumberOfPages();
      pdf.setFontSize(10);
      for (let p = 1; p <= totalPages; p++) {
        pdf.setPage(p);
        const footerY = pageHeight - 8;
        pdf.setTextColor(22, 166, 55);
        pdf.text('Generated by UniApplyForMe', margin, footerY);
        pdf.setTextColor(9, 94, 65);
        pdf.text(`Page ${p} of ${totalPages}`, pageWidth / 2, footerY, { align: 'center' });
        pdf.text('apply.org.za', pageWidth - margin - 20, footerY);
      }

      pdf.save(`${file.name || 'document'}.pdf`);
      toast.success(`PDF saved: ${file.name || 'document'}.pdf`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to generate PDF. Please try again.');
    } finally {
      if (tempDiv && document.body.contains(tempDiv)) document.body.removeChild(tempDiv);
      setIsGenerating(false);
    }
  };

  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(plainText);
      setCopied(true);
      toast.success('Text copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy text');
    }
  };

  return (
    <div className="w-full mb-6">
      <div className="rounded-2xl border border-white/80 bg-white/80 backdrop-blur shadow-lg overflow-hidden">
        <Tabs value={viewMode} onValueChange={(v) => setViewMode(v as 'rendered' | 'text')}>

          {/* ── Toolbar ── */}
          <div className="bg-gradient-to-r from-primary/10 to-secondary/10 border-b border-primary/10 px-4 sm:px-5 py-4">
            {/* File info row */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3 min-w-0">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/15 flex-shrink-0">
                  <FileText className="w-5 h-5 text-primary" />
                </div>
                <div className="min-w-0">
                  <p className="text-[11px] font-medium text-gray-500 uppercase tracking-wide">Your file</p>
                  <h2 className="text-sm sm:text-base font-bold text-secondary truncate">{file.name}</h2>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0 ml-3">
                <span className="text-xs text-gray-400 hidden sm:block">
                  {(file.size / 1024).toFixed(1)} KB
                </span>
                <button
                  onClick={onClose}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white/80 px-3 py-1.5 text-xs font-medium text-gray-600 hover:border-gray-300 hover:bg-white transition-all"
                >
                  <X className="w-3.5 h-3.5" />
                  New file
                </button>
              </div>
            </div>

            {/* Controls row */}
            <div className="flex items-center gap-3 flex-wrap">
              <TabsList className="bg-white/80 border border-gray-200 rounded-xl p-1 h-auto gap-0.5">
                <TabsTrigger value="rendered" className="rounded-lg px-3 py-1.5 text-xs sm:text-sm gap-1.5">
                  <Eye className="w-3.5 h-3.5" />
                  Document
                </TabsTrigger>
                <TabsTrigger value="text" className="rounded-lg px-3 py-1.5 text-xs sm:text-sm gap-1.5">
                  <Type className="w-3.5 h-3.5" />
                  Plain Text
                </TabsTrigger>
              </TabsList>

              <button
                onClick={convertToPDF}
                disabled={isGenerating}
                className="ml-auto inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs sm:text-sm font-semibold text-white shadow-md shadow-primary/25 hover:bg-primary/90 active:scale-95 transition-all disabled:opacity-60 disabled:cursor-not-allowed"
              >
                <Download className="w-4 h-4" />
                {isGenerating ? 'Preparing…' : 'Download PDF'}
              </button>
            </div>
          </div>

          {/* ── Content panels ── */}
          <div className="p-4 sm:p-5">
            <TabsContent value="rendered" className="mt-0">
              <div ref={contentRef}>
                <iframe
                  title="Document preview"
                  className="w-full min-h-[60vh] rounded-xl border border-gray-200 bg-white shadow-inner"
                  sandbox="allow-same-origin allow-popups"
                  referrerPolicy="no-referrer"
                  srcDoc={previewDocument}
                />
              </div>
            </TabsContent>

            <TabsContent value="text" className="mt-0">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <p className="text-xs text-gray-500">Plain-text extraction — select all and copy, or use the button.</p>
                  <button
                    onClick={handleCopyText}
                    className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-semibold transition-all
                      ${copied
                        ? 'border-primary/30 bg-primary/10 text-primary'
                        : 'border-gray-200 bg-white text-gray-700 hover:border-primary/40 hover:bg-primary/5'
                      }`}
                  >
                    {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? 'Copied!' : 'Copy text'}
                  </button>
                </div>
                <div className="rounded-xl border border-gray-200 bg-gray-50 p-4 max-h-[60vh] overflow-auto">
                  <pre className="whitespace-pre-wrap font-sans text-sm text-gray-800 break-words leading-relaxed">
                    {plainText}
                  </pre>
                </div>
              </div>
            </TabsContent>
          </div>

          {/* ── Hint bar ── */}
          <div className="border-t border-gray-100 bg-gray-50/60 px-4 sm:px-5 py-2.5 flex items-center gap-2 text-xs text-gray-500">
            <Lightbulb className="w-3.5 h-3.5 flex-shrink-0 text-amber-400" />
            Switch between Document and Plain Text views, or download a clean PDF copy.
          </div>
        </Tabs>
      </div>
    </div>
  );
}
